//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banks_H__Martin__C__Pd_thru_date
    {
        public string Handling_Atty { get; set; }
        public string Credit_Atty { get; set; }
        public string Status_Code { get; set; }
        public int Reference_Number { get; set; }
        public string Client_Name { get; set; }
    }
}
