//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FeesPackageEntities : DbContext
    {
        public FeesPackageEntities()
            : base("name=FeesPackageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ReferralwithClient> ReferralwithClients { get; set; }
        public virtual DbSet<tblInsurance> tblInsurances { get; set; }
        public virtual DbSet<tblAttorney> tblAttorneys { get; set; }
        public virtual DbSet<tblAttorneyCombo> tblAttorneyCombos { get; set; }
        public virtual DbSet<tblAttyDesc> tblAttyDescs { get; set; }
        public virtual DbSet<tblCounty> tblCounties { get; set; }
        public virtual DbSet<tblReferral> tblReferrals { get; set; }
        public virtual DbSet<tblClient> tblClients { get; set; }
        public virtual DbSet<tblClaim> tblClaims { get; set; }
        public virtual DbSet<qryClaim> qryClaims { get; set; }
        public virtual DbSet<tblPaymentFrequency> tblPaymentFrequencies { get; set; }
        public virtual DbSet<tblStatusCode> tblStatusCodes { get; set; }
        public virtual DbSet<tblClientReferral> tblClientReferrals { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
    }
}
