//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FeesPackageEntities : DbContext
    {
        public FeesPackageEntities()
            : base("name=FeesPackageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ReferralwithClient> ReferralwithClients { get; set; }
        public virtual DbSet<tblInsurance> tblInsurances { get; set; }
        public virtual DbSet<tblAttorney> tblAttorneys { get; set; }
        public virtual DbSet<tblAttorneyCombo> tblAttorneyCombos { get; set; }
        public virtual DbSet<tblAttyDesc> tblAttyDescs { get; set; }
        public virtual DbSet<tblCounty> tblCounties { get; set; }
        public virtual DbSet<tblReferral> tblReferrals { get; set; }
        public virtual DbSet<tblClient> tblClients { get; set; }
        public virtual DbSet<tblClaim> tblClaims { get; set; }
        public virtual DbSet<qryClaim> qryClaims { get; set; }
        public virtual DbSet<tblPaymentFrequency> tblPaymentFrequencies { get; set; }
        public virtual DbSet<tblStatusCode> tblStatusCodes { get; set; }
        public virtual DbSet<tblClientReferral> tblClientReferrals { get; set; }
        public virtual DbSet<tblPayment> tblPayments { get; set; }
        public virtual DbSet<qryClaims_30Days> qryClaims_30Days { get; set; }
        public virtual DbSet<qryClaims_30Days2> qryClaims_30Days2 { get; set; }
        public virtual DbSet<qryClaimsDormant> qryClaimsDormants { get; set; }
        public virtual DbSet<qryClaimsDormant2> qryClaimsDormant2 { get; set; }
    
        public virtual int sp_PostPayments(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, ObjectParameter cnt, ObjectParameter amt, ObjectParameter rowCount)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_PostPayments", fromDateParameter, toDateParameter, cnt, amt, rowCount);
        }
    }
}
