//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryClaim
    {
        public string Claim_No { get; set; }
        public string Adjuster { get; set; }
        public string Atty_Combo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Frequency { get; set; }
        public string Status { get; set; }
        public Nullable<int> Reference_Number { get; set; }
    }
}
