//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryClaim_Without_Matching_tblPayment
    {
        public Nullable<int> tblClaim_Reference_Number { get; set; }
        public string Claim_Number { get; set; }
        public Nullable<decimal> Payment_Amount { get; set; }
        public string Payment_Frequency { get; set; }
        public Nullable<int> tblClaim_Reference_Number_2 { get; set; }
    }
}
