//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryClientClaimListteststatu
    {
        public int Reference_Number { get; set; }
        public string Client_Name { get; set; }
        public string Handling_Atty { get; set; }
        public Nullable<double> Handling__ { get; set; }
        public string Credit_Atty { get; set; }
        public Nullable<double> Credit__ { get; set; }
        public string Claim_Number { get; set; }
        public string Insurance_Contact { get; set; }
        public Nullable<decimal> Payment_Amount { get; set; }
        public string Payment_Frequency { get; set; }
        public string Status_Code { get; set; }
    }
}
