//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryMonthlyIncome__AJS_Weeklies__no_posted_yet
    {
        public string Claim_Number { get; set; }
        public string Client_Name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Input_Date { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public Nullable<double> Expr2 { get; set; }
        public string Expr4 { get; set; }
    }
}
