//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PMTS_with_Comment
    {
        public Nullable<int> Reference_Number { get; set; }
        public string Claim_Number { get; set; }
        public System.DateTime Date_Payment { get; set; }
        public Nullable<System.DateTime> Period_From { get; set; }
        public Nullable<System.DateTime> Period_To { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Input_Date { get; set; }
        public string Item_Comment { get; set; }
    }
}
