//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttorneyCombo
    {
        public Nullable<double> Deposit_Options { get; set; }
        public string Attorney_Combinations { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual tblAttyDesc tblAttyDesc { get; set; }
    }
}
