//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblC_R
    {
        public int ID { get; set; }
        public Nullable<int> Reference_Number { get; set; }
        public string Claim_Number { get; set; }
        public Nullable<System.DateTime> C_RDate { get; set; }
    }
}
