//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientReferral
    {
        public int Reference_Number { get; set; }
        public string Client_Referral_Atty { get; set; }
        public Nullable<double> Client_Referral__ { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
