//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeesPackage.Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReferral
    {
        public string Referral_Name { get; set; }
        public string Referral_Firm { get; set; }
        public string Referral_Tax_ID { get; set; }
        public string Referral_Credit_Atty { get; set; }
    }
}
